### PR TITLE
Implement UI of new landing page

### PR DESCRIPTION
**Pull request by aar0nTw**
### New Landing page landed

Screen Shot 2021-03-31 at 7 55 52 PM

image tag ~`ch16087-6c6ad826`~ `ch16087-77c46901`

### CODE REVIEW

**Comment by ggosiang** [comment]
clicking on `Create New Job`, it will go to `https://hub.ericy3.aws.primehub.io/console/g/phusers/jobs` instead of `https://hub.ericy3.aws.primehub.io/console/g/phusers/job?page=1`
螢幕快照 2021-04-01 下午3 16 50

also, seems the recent time info is weird
螢幕快照 2021-04-01 下午3 15 59
(timezone is correct)
螢幕快照 2021-04-01 下午3 16 20

**Comment by aar0nTw** [comment]
@ggosiang updated, wait for tag `ch16087-8860346e`

**Review by ctiml — APPROVED** [review]
LGTM

**Comment by ggosiang** [comment]
LGTM

**Review by ggosiang — APPROVED** [review]

**Pull request merged**
