### PR TITLE
Feature/ch11773/show empty page if no group is available

### PR DESCRIPTION
**Pull request by aar0nTw**
Screen Shot 2020-08-25 at 4 45 11 PM

image tag name `ch11773-c01ba22d`

### CODE REVIEW

**Comment by popcornylu** [comment]
There is a transient state when entering the root page. 

Click the primehub logo, and we can see the transient state as below.
image

**Comment by popcornylu** [comment]
When i reload a page in the url
https://hub.celu.aws.primehub.io/console/g/phusers/job/job-202008240838-f203xj

it will redirect to 
-> https://hub.celu.aws.primehub.io/console/g
-> https://hub.celu.aws.primehub.io/console/g/phusers

expeacted

**Comment by popcornylu** [comment]
Click the home will go to `https://hub.celu.aws.primehub.io/g` and showing
image

**Comment by aar0nTw** [comment]
@popcornylu fixed `ch11773-9abc0850`

**Pull request merged**
