### PR TITLE
Add shared space proxy to tusd

### PR DESCRIPTION
**Pull request by jackklpan**
implement `/api/tus` endpoint for
* proxy to internal tusd
* check if a user could upload to the target `group` (by `dirpath` field)

### CODE REVIEW

**Comment by jackklpan** [comment]
How to test:
```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Uppy</title>
    <link href="https://releases.transloadit.com/uppy/v1.23.3/uppy.min.css" rel="stylesheet">
  </head>
  <body>
    <div id="drag-drop-area"></div>

    <script src="https://releases.transloadit.com/uppy/v1.23.3/uppy.min.js"></script>
    <script>
      var uppy = Uppy.Core()
        .use(Uppy.Dashboard, {
          inline: true,
          target: '#drag-drop-area'
        })
        .use(Uppy.Tus, {endpoint: 'GRAPHQL_ENDPOINT/APP_PREFIX/tus'})

      uppy.on('complete', (result) => {
        console.log('Upload complete! We’ve uploaded these files:', result.successful)
      })
    </script>
  </body>
</html>
```

**Comment by jackklpan** [comment]
Image Tag: `ch14161-9b9ab6bb`

**Comment by qrtt1** [comment]
new graphql tag `ch14161-3ffc79cd`

**Comment by qrtt1** [comment]
graphql tag `ch14161-a805618f`

**Comment by qrtt1** [comment]
graphql tag `ch14161-4c0522ee`

**Review by ctiml — APPROVED** [review]
LGTM

**Pull request merged**
