### PR TITLE
Remove user volume capcity in gorup setup

### PR DESCRIPTION
**Pull request by aar0nTw**
Signed-off-by: Aaron Huang <aaroms9733@gmail.com>

### CODE REVIEW

**Comment by aar0nTw** [comment]
`ch11231-76bd7c0`

**Comment by popcornylu** [comment]
1. User -> Edit phadmin
    image

2. Image -> Add   
   image

3. InstanceTyep -> Add    
   image

Please remove the related query from graphql.
image

**Comment by popcornylu** [comment]
primehub-controller use the userVolumeCapacity in group
https://github.com/InfuseAI/primehub-controller/blob/master/pkg/graphql/graphql.go#L181

Can we keep the `group.userVolumeCapacity` for backward compatibility?

**Comment by popcornylu** [comment]
LGTM

**Pull request merged**
