### PR TITLE
Refactor the shared space browse api

### PR DESCRIPTION
**Pull request by jackklpan**
Signed-off-by: Jack Pan <jackpan@infuseai.io>

### CODE REVIEW

**Comment by jackklpan** [comment]
Image Tag: `ch14724-f699720f`

**Comment by popcornylu** [comment]
I found that the prefix format is inconsistent between artifact and file
image

**Comment by jackklpan** [comment]
> I found that the prefix format is inconsistent between artifact and file (tailing slash)
> image

**Comment by jackklpan** [comment]
Which one do you think is more reasonable?
I think we use the trailing slash to represent the folder.

**Comment by popcornylu** [comment]
In the list api
1. If recursive is false, could we have the same result for prefix="" and prefix="/"
2.If recursive is false, could we have the same result for prefix="path/to/subfolder" and prefix="path/to/subfolder/"
3. I think it is a abnormal result
    image 
4. In order to make the api consistent, can we change the where field from `prefix` to `phfsPrefix`

**Comment by jackklpan** [comment]
Fix the comments. Thanks!

**Comment by popcornylu** [comment]
The lastModified format is not the same. Should be iso8601 format.

image

**Pull request merged**
