### PR TITLE
feat(secret): drop canner and refactor

### PR DESCRIPTION
**Pull request by neighborhood999**
#### List secrets
Kapture 2021-07-27 at 11 03 16

#### Browse and update secret information
Kapture 2021-07-27 at 11 11 16

#### Delete a secret
Kapture 2021-07-27 at 11 12 33

#### Create a secret
Kapture 2021-07-27 at 17 24 57

## Descriptions

- Drop canner related dependencies
- Refactoring layouts and extract common components
- Adding more UI status to display component current status
- Adding `useRoutePrefix` hook that can be used in any component
- Adjustment the eslint rules
- Adding test cases

Signed-off-by: Jie Peng <im@jiepeng.me>

** PR checklist **

- [x] Ensure you have added or ran the appropriate tests for your PR.
- [x] DCO signed

### CODE REVIEW

**Comment by ggosiang** [comment]
reviewed and found two issues

1. it will direct to a blank page while accessing add, edit, or back-to-secert pages
    - https://hub.xxx.aws.primehub.io/admin/secret?operator=create
    - https://hub.xxx.aws.primehub.io/admin/secret/gitsync-secret-test-d1
    - https://hub.xxx.aws.primehub.io/admin/secret

    (manually adjust it to `.../console/admin/secret...` can solve this issue)

2. the secret data is not saved
(add a secret)
1-add
(edit a secret)
2-edit

**Comment by neighborhood999** [comment]
> reviewed and found a issue
> 
>     * it will direct to a blank page while accessing add, edit, or back-to-secert pages
>       
>       * [hub.xxx.aws.primehub.io/admin/secret?operator=create](https://hub.xxx.aws.primehub.io/admin/secret?operator=create)
>       * [hub.xxx.aws.primehub.io/admin/secret/gitsync-secret-test-d1](https://hub.xxx.aws.primehub.io/admin/secret/gitsync-secret-test-d1)
>       * [hub.xxx.aws.primehub.io/admin/secret](https://hub.xxx.aws.primehub.io/admin/secret)
>       
>       (manually adjust it to `.../console/admin/secret...` can solve this issue)

Thanks for raising the issue, this problem is related to the route prefix, because I did some refactoring in this PR, I will fix it.

**Comment by ggosiang** [comment]
tested route prefix and successfully create secret for pulling image, just found a small issue
1. create a new secret

1. update this secret with different username and password then click Save button

1. check this secret but found old data (reload page can get updated data)

**Comment by neighborhood999** [comment]
> tested route prefix and successfully create secret for pulling image, just found a small issue
> 
>     1. create a new secret
>        
> 
>     2. update this secret with different username and password then click Save button
>        
> 
>     3. check this secret but found old data (reload page can get updated data)
>        

Thanks for testing, found problems, and fixed.

**Review by ggosiang — APPROVED** [review]

**Review by aar0nTw — APPROVED** [review]

**Pull request merged**
