### PR TITLE
Feature/ch14897/console supports to create a custom image

### PR DESCRIPTION
**Pull request by aar0nTw**

### CODE REVIEW

**Comment by popcornylu** [comment]
please fit the ci and provide the review image.

**Comment by aar0nTw** [comment]
`ch14897-eafa8ae7`

**Comment by popcornylu** [comment]
Bug: A non group-admin can see the image submenu.

Current:
See the images submenu
image
Click the new image button, it will go back to home

Expected:
Should not see the images submenu

**Comment by popcornylu** [comment]
If i use console with `ch14897-eafa8ae7` and graphql with `latest`, when i create image and the new created image list is not shown.

**Comment by popcornylu** [comment]
For the normal building process, there are some problem

1. When building, the image list does not shown not ready icon. Please see the spec and there is a warning icon next to the image.
    https://www.notion.so/infuseai/Spec-Build-Custom-Group-Image-7a95b58133c141b293099b6607853779#19e31d3ff81445d99ae4a04eed2bef53
1. When a image is created, we should not change the image between "From existing one" and "Build custom image"
1. When a image is building, we should keep refresh the building state
    https://www.notion.so/infuseai/Spec-Build-Custom-Group-Image-7a95b58133c141b293099b6607853779#f72936ad753648aeb6d45cb90a7a5403
 1. I cannot see the log, it keeps showing loading.
    截圖 2021-02-18 14 05 30
1. When entering the image build page, if the building is completed and then click the rebuild button, could it back to the image detail page rather than image list page?
1. When entering the image build page, if it is building and then click the cancel button, could it back to the image detail page rather than image list page?

**Comment by aar0nTw** [comment]
> Bug: A non group-admin can see the image submenu.
> 
> ## Current
> See the images submenu
> image
> Click the new image button, it will go back to home
> 
> ## Expected
> Should not see the images submenu



> Bug: A non group-admin can see the image submenu.
> 
> ## Current
> See the images submenu
> image
> Click the new image button, it will go back to home
> 
> ## Expected
> Should not see the images submenu

resolved.

**Comment by aar0nTw** [comment]
Update list
- [x] Image item should hide if not groupAdmin
- [x] general group admin can not get imageConnection if not system admin
- [x] show image not ready warn icon in image list
- [ ] disable radio item switchable between  "From existing one" and "Build custom image" when image created already.
- [ ] keep refresh the building state when image building
- [ ] back to detail page when dismiss building detail dialog

Others:

the log stuff not on list above, it will put to ch15467 and wait the ce logCtrl finish.

**Comment by aar0nTw** [comment]
`ch14897-0d945a44`

**Comment by aar0nTw** [comment]
`ch14897-742a8b7d`

**Comment by aar0nTw** [comment]
`ch14897-fa05b1f3`

**Comment by popcornylu** [comment]
Merged

**Pull request merged**
