### PR TITLE
subset the launchGroupOnly for dataset

### PR DESCRIPTION
**Pull request by ggosiang**
Signed-off-by: ericy <ericy@infuseai.io>

### CODE REVIEW

**Comment by ggosiang** [comment]
image: ch11020-f677cc8

**Comment by popcornylu** [comment]
1. Set the launchGroupOnly default value to false if the annotation is absent.
1. Always add the annotation when creating a new dataset and value is true

**Comment by ggosiang** [comment]
image: ch11020-e3b44d3

**Comment by popcornylu** [comment]
LGTM

**Pull request merged**
