### PR TITLE
Feature/ch15467/implement the image job log api

### PR DESCRIPTION
**Pull request by aar0nTw**
- [x] ImageSpecJob Log endpoint
- [x] access control ( Only group admin can use it)
- [x] test

### CODE REVIEW

**Comment by aar0nTw** [comment]
test image: `ch15467-b3ee1e4c`

**Comment by popcornylu** [comment]
I cannot get the log successfully.
image

**Comment by aar0nTw** [comment]
`ch15467-ab36acaf`

**Comment by aar0nTw** [comment]
CI fixed

`ch15467-0b71d11d`

**Comment by popcornylu** [comment]
LGTM

**Pull request merged**
