### PR TITLE
fix(shareFiles): customizable folder path

### PR DESCRIPTION
**Pull request by neighborhood999**
## Screenshot

https://user-images.githubusercontent.com/10325111/147531715-6ae6ed94-984a-4940-a0d0-273e77acde63.mp4

## Description

- Customizable folder path

## Image

- `sc23940-1f0ac052`

Signed-off-by: Jie Peng <im@jiepeng.me>

**PR checklist**

- [x] Ensure you have added or ran the appropriate tests for your PR.
- [x] DCO signed

### CODE REVIEW

**Comment by ggosiang** [comment]
1. suggest appending the `/` symbol after the selected folder, in this example, change the `iris` to `iris/`
2. in the `add folder` mode, suggest making the `add files to dataset` button to be disabled

i

**Review by popcornylu — COMMENTED** [review]
Or can we use this style when we add folder?
1. Can we use the addon before to make sure that the user cannot change  the folder.
   image
   https://3x.ant.design/components/input/
2. Should prevent to show "Add folder" before the user select one dataset.
3. Can we use "Change path" instead of "Add folder"?

**Comment by neighborhood999** [comment]
> 1. suggest appending the `/` symbol after the selected folder, in this example, change the `iris` to `iris/`
> 
>     2. in the `add folder` mode, suggest making the `add files to dataset` button to be disabled
> 
> 
> i

Thanks for reviewing, I applied your suggestion.

@popcornylu The design has already been confirmed with @hbshih , if you want to change the design I think we should discuss it with Ben.

**Comment by hbshih** [comment]
> Or can we use this style when we add folder?
> 
> 1. Can we use the addon before to make sure that the user cannot change  the folder.
>    image
>    https://3x.ant.design/components/input/
> 2. Should prevent to show "Add folder" before the user select one dataset.
> 3. Can we use "Change path" instead of "Add folder"?

@popcornylu 
For 1., do you think we should prevent users from changing folders? I designed it this way as I thought it would also be nice for the user to change the path in a more flexible way so wonder about your thoughts on this. 

For the 3. suggestion, @ggosiang and I thought "Add Folder" would be easier for users to understand what's that function about. Changing path or add path might be difficult to understand in this case so we suggest to use "Add Folder"

**Just one suggestion here:**
Instead of showing the full path when adding a new folder, maybe we could just show the parent directory?

So in the case of PJ's screen recording:
Instead of showing `pj-test2/hij/...` When the "Add Folder" button is tapped.

Just show `hij/...` might be easier for the users to understand the concept

**Comment by ggosiang** [comment]
LGTM! just want to discuss a scenario while users cancel their `add-folder` action

if users choose to add a folder and type in the new folder name, then they click on the cancel button
Screen Shot 2022-01-03 at 10 27 58


and then click `add to existing dataset` again, the mode is still in `add-folder` but the value is empty 
Screen Shot 2022-01-03 at 10 28 09

should we `keep the value of the new dataset` or `always make the select-folder mode by default` while users cancel their action?

**Comment by neighborhood999** [comment]
> 

Thanks for testing, i forgot to reset the custom path state. below is the updated recording:

Kapture 2022-01-03 at 10 56 39

**Review by ggosiang — APPROVED** [review]

**Pull request merged**
